import type { RoomId, RoomGroup } from '@/types/room.types';
import type { RoomContent } from '@/lib/content/visitorRooms';

const KO: Record<RoomId, Partial<RoomContent>> = {
  bottleneck:{title:'컴퓨트 병목이 있습니다',label:'컴퓨트 병목',summary:'비용이 커지는 워크로드를 설명하고 구조적 관점의 검토를 받아보세요.',audience:'컴퓨트 비용·속도·에너지가 한계가 되는 팀',intro:'워크로드에서 시작합니다. 어디서 실행되고 무엇이 비싸지는지 알려주면, 견적이 아니라 구조적 진단을 제공합니다.',offers:['비용이 실제로 어디에 있는지 표현 수준에서 검토','문제가 어떤 ALPHA 계층과 관련될 수 있는지와 그 이유','적합한 워크로드에서 가능한 범위를 보수적으로 설명'],ctaLabel:'검토 시작하기'},
  'technical-assessment':{title:'기술 평가를 원합니다',label:'기술 평가',summary:'PoC나 상업적 결과를 가정하지 않고 실제 워크로드 하나를 집중적으로 검토합니다.',audience:'실제 워크로드에서 접근법을 시험할 준비가 된 팀',intro:'ALPHA Compute 평가는 하나의 워크로드를 대상으로 계산 경계, 우선순위가 있는 Boundary Waste Map, 다음 증거 단계에 대한 권고를 다룹니다. 기밀 교환에는 적절한 보호와 명시적 권한이 필요하며 PoC는 별도로 선택되는 단계입니다.',offers:['한 워크로드의 Boundary Waste Map','ALPHA Compute 관련성을 우선순위로 정리','추가 조치 없음까지 포함한 다음 증거 단계 권고'],ctaLabel:'ALPHA Compute 평가 요청'},
  technical:{title:'기술 세부 내용을 보고 싶습니다',label:'기술',summary:'PRISM, AXIOM, AXIOM-TENSOR, CRE, FQNM, QNTA의 공개 설명과 공개 경계를 확인하세요.',audience:'접근법을 평가하는 엔지니어와 응용 연구자',intro:'각 기술의 공개 설명, Representation → Observation → Transfer → Execution → Reconstruction 관점과 공개 근거를 제공합니다. 제한된 메커니즘이나 벤치마크는 명시적 권한과 필요한 계약이 있을 때만 공유됩니다.',offers:['PRISM, AXIOM, AXIOM-TENSOR, CRE, FQNM, QNTA의 공개 설명','FQNM 공개 프리프린트','공개 자료와 권한 제한 자료의 경계'],ctaLabel:'기술 살펴보기'},
  research:{title:'연구자입니다',label:'연구',summary:'협업, 검증, 방법을 뒷받침하는 공개 연구를 살펴보세요.',audience:'학계 및 기관 연구자',intro:'공개된 연구, 검증 방식, itriX와의 연구 협업이 어떻게 구성될 수 있는지 설명합니다.',offers:['FQNM 공개 프리프린트와 그 범위','독립 검증 접근법','협업 논의 경로'],ctaLabel:'FQNM 프리프린트 읽기'},
  architecture:{title:'칩 또는 가속기를 설계합니다',label:'아키텍처',summary:'재구성된 계산이 CPU, GPU, NPU, 엣지 또는 커스텀 실리콘과 어떻게 맞물릴 수 있는지 살펴봅니다.',audience:'반도체 및 가속기 아키텍트',intro:'구조 보존 소프트웨어 계층이 하드웨어 아키텍처와 어떻게 맞물릴 수 있는지 검토합니다. ALPHA Compute가 먼저 표현 가설을 세우며, ALPHA Core는 근거가 더 깊은 실행 검증을 뒷받침할 때만 고려됩니다.',offers:['표현이 아키텍처와 맞물리는 방식','ALPHA Core 실행 검증이 관련될 수 있는 조건','논의에서 평가로 가는 선택 가능한 경로'],ctaLabel:'아키텍처 논의 요청'},
  investor:{title:'투자자입니다',label:'투자자',summary:'핵심 명제, 자산 경량 모델, 근거 규율과 승인된 투자자 정보 경로를 살펴봅니다.',audience:'기회를 평가하는 투자자',intro:'컴퓨팅 인프라 명제, IP 및 라이선싱 모델, 회사의 근거 규율을 공개 가능한 범위에서 설명합니다. 수치와 제한 자료는 적절한 승인 채널을 통해서만 공유됩니다.',offers:['인프라 명제 요약','IP 중심의 자산 경량 모델','승인된 투자자 자료를 위해 팀에 연락하는 방법'],ctaLabel:'투자자 브리핑 요청'},
  partner:{title:'파트너십을 논의하고 싶습니다',label:'파트너',summary:'통합, 공동 개발 및 전략적 파트너십 질문을 살펴봅니다.',audience:'하드웨어, 클라우드 및 플랫폼 파트너',intro:'표현 가설을 하드웨어 및 런타임 파트너와 어떻게 평가할 수 있는지, ALPHA Core 실행 검증이 언제 관련될 수 있는지, 어떤 질문이 명시적 계약을 필요로 하는지 설명합니다.',offers:['아키텍처 및 실행 검증 질문','가능한 협업 질문','서면 계약이 필요한 사항'],ctaLabel:'파트너십 대화 시작'},
  shareholder:{title:'주주입니다',label:'주주',summary:'방향, 마일스톤, 회사가 향하는 곳을 살펴봅니다.',audience:'기존 주주',intro:'방향과 마일스톤을 높은 수준에서 제공합니다. 상세 업데이트는 공식 채널을 통해 공유됩니다.',offers:['전략 방향 요약','마일스톤 프레이밍','상세 내용을 위한 공식 연락 경로'],ctaLabel:'팀에 연락하기'},
  'public-infrastructure':{title:'공공 인프라 분야에서 일합니다',label:'공공 인프라',summary:'공공 및 대규모 시스템에서 지속 가능한 컴퓨팅의 관련성을 살펴봅니다.',audience:'공공 부문 및 대규모 인프라 책임자',intro:'표현 우선 계산이 공공 인프라 규모의 에너지와 비용에 왜 관련될 수 있는지 보수적으로 설명합니다.',offers:['지속 가능한 컴퓨팅 관련성','대규모 환경에서의 적용 질문','구조화된 대화로 가는 경로'],ctaLabel:'검토 시작'},
  'sustainable-ai':{title:'에너지가 실제 제약입니다',label:'지속 가능한 AI',summary:'하드웨어를 늘리기 전에 계산을 재구성해 에너지 부담을 줄일 수 있는지 검토합니다.',audience:'인프라 및 데이터센터 전략 담당자',intro:'실리콘이 아니라 전력이 제약일 때, 인프라 확장 전에 계산 구조를 바꿔 에너지 부담 일부를 줄일 수 있는지 검토합니다. 성능이나 절감은 미리 가정하지 않습니다.',offers:['피할 수 있는 작업에 에너지가 쓰이는 지점','표현 우선 접근이 하드웨어 요구량과 어떤 관련이 있는지','ALPHA Core 검증이 정당화될 수 있는 조건'],ctaLabel:'지속 가능한 AI 인프라 살펴보기'},
  media:{title:'미디어 관계자입니다',label:'미디어',summary:'정확한 공개 프레이밍, 핵심 명제와 공개 가능한 범위를 확인하세요.',audience:'기자 및 분석가',intro:'itriX가 무엇을 하는지에 대한 정확한 공개 설명을 제공합니다. 제한된 메커니즘 세부 정보와 비공개 수치는 공개하지 않습니다.',offers:['정확한 한 줄 및 문단 설명','공개 가능한 것과 아닌 것','언론 연락 경로'],ctaLabel:'미디어 / 스토리 키트 요청'},
  story:{title:'이 이야기를 전달하고 싶습니다',label:'스토리',summary:'정확한 프레이밍, 인용문과 공개 가능한 내용을 담은 스토리 키트입니다.',audience:'기자, 스토리텔러 및 설명자',intro:'itriX 이야기를 정확하게 전달하기 위한 공개 명제, 유효한 비유, 승인된 프레이밍과 공개 경계를 제공합니다.',offers:['승인된 공개 프레이밍과 인용문','유효한 비유','피해야 할 주장'],ctaLabel:'스토리 키트 요청'},
  orientation:{title:'둘러보는 중입니다',label:'오리엔테이션',summary:'정해진 목적 없이 핵심 아이디어에서 시작해 원하는 방향으로 살펴보세요.',audience:'itriX를 처음 접하는 누구나',intro:'핵심 명제에서 시작해 자신의 속도로 제품, 기술, 공개 자료 또는 질문으로 이동하세요. 영업 관계를 가정하지 않습니다.',offers:['아이디어 한 줄 요약','다음에 볼 수 있는 곳의 지도','압박 없는 탐색'],ctaLabel:'itriX의 관점 보기'},
};

export const ROOM_GROUP_LABEL_KO: Record<RoomGroup,string>={operator:'문제에서 시작',technical:'기술 깊이 보기',capital:'자본 및 파트너십',communications:'이야기 전달',orientation:'둘러보기'};
export function roomCopy(locale:string,room:RoomContent):RoomContent{return locale==='ko'?{...room,...KO[room.id],offers:(KO[room.id].offers as string[]|undefined)??room.offers}:room;}
