import type { UseCase } from '@/lib/content/useCases';
const KO: Record<string, Partial<UseCase>>={
'inference-cost':{audience:'클라우드, 하이퍼스케일러 및 AI 제품 팀',headline:'사용자가 늘 때마다 비용도 커질 때',situation:'모델은 작동하고 사용량은 늘지만 컴퓨트 비용도 함께 커집니다. 하드웨어 증설은 여유를 줄 수 있지만 작업 단위의 근본 비용을 바꾸지는 않습니다.',approach:'itriX는 먼저 계산이 실행되기 전에 올바른 형태로 표현되어 있는지 묻습니다. ALPHA Compute는 표현·데이터 이동·구조적 비용 가설을 검토하며, ALPHA Core는 검증된 표현 가설이 있을 때만 목표 실행 환경에서 추가 검증을 고려합니다.',startsWith:'공개 기술 검토 또는 ALPHA Compute 평가 가능성부터.',ctaLabel:'이 워크로드 검토'},
'slow-or-drifting-simulations':{audience:'HPC, CAE 및 과학 계산 책임자',headline:'실행이 너무 길거나 결과 신뢰도가 서서히 흔들릴 때',situation:'장시간 시뮬레이션이 매우 오래 걸리거나 보존되어야 할 양이 시간이 지나며 드리프트해 결과를 신뢰하기 어려워집니다.',approach:'itriX는 하드웨어뿐 아니라 계산 구조가 제약인지 검토합니다. 보존이 핵심인 선택된 문제에서는 FQNM의 현재 입증 범위와 맞는지 평가할 수 있습니다. 적합성이나 성능 향상은 사전에 가정하지 않습니다.',startsWith:'기술 검토 또는 별도로 선택된 통제 평가.',ctaLabel:'기술 검토 요청'},
'energy-and-cooling':{audience:'인프라 및 데이터센터 전략 담당자',headline:'실리콘보다 전력이 제약일 때',situation:'칩을 더 살 수 있어도 전력, 냉각, 공간을 쉽게 늘릴 수 없습니다. 에너지가 AI 역량 확장의 실제 한계가 됩니다.',approach:'itriX는 인프라를 확장하기 전에 계산 표현을 재구성해 피할 수 있는 작업을 줄일 수 있는지 검토합니다. ALPHA Compute가 먼저 구조적 가설을 세우며 ALPHA Core는 그 가설이 검증되고 더 깊은 실행 검증이 정당화될 때만 관련됩니다.',startsWith:'ALPHA Compute 관점의 구조적 검토부터.',ctaLabel:'지속 가능한 AI 인프라 살펴보기'},
'chip-software-stack':{audience:'반도체 및 가속기 파트너',headline:'하드웨어는 강하지만 워크로드 형태가 맞지 않을 때',situation:'실리콘은 강력해도 워크로드가 비효율적인 형태로 도착하면 뛰어난 하드웨어도 피할 수 있는 작업에 자원을 씁니다.',approach:'itriX는 먼저 ALPHA Compute 관점에서 표현 가설이 성립하는지 검토합니다. 그 가설에 근거가 있을 때만 ALPHA Core를 통해 특정 CPU, GPU, NPU, 엣지 또는 커스텀 환경에서 실행 적합성을 검증할 수 있습니다.',startsWith:'아키텍처 논의와 표현 가설 검토부터. ALPHA Core는 자동 다음 단계가 아닙니다.',ctaLabel:'아키텍처 논의 요청'},
'edge-headroom':{audience:'로보틱스 및 엣지 AI 팀',headline:'전력·메모리·열 예산에 더 이상 여유가 없을 때',situation:'로봇이나 엣지 장치에서는 하드웨어를 쉽게 추가할 수 없습니다. 전력, 메모리, 열 예산은 제한되어 있지만 실행하려는 모델은 더 무거워집니다.',approach:'itriX는 제약 장치에 도달하기 전에 계산을 더 적합한 형태로 재구성할 수 있는지 검토합니다. ALPHA Compute가 가능성을 진단하고, 검증된 가설이 있을 때 ALPHA Core가 목표 환경에서 실행을 검증할 수 있습니다.',startsWith:'ALPHA Compute 구조 검토부터.',ctaLabel:'엣지 워크로드 검토'},
'reproducibility':{audience:'연구 및 규제 산업 팀',headline:'같은 입력이 조용히 다른 답을 만들 때',situation:'같은 워크로드를 다른 머신이나 정밀도에서 실행했을 때 결과가 달라져 신뢰가 흔들릴 수 있습니다.',approach:'itriX는 변환과 실행 과정에서 중요한 구조를 보존할 수 있는 표현이 관련되는지 검토합니다. FQNM과 같은 방법은 각자의 제한된 적용 범위가 있으며, 재현성이나 정확성 향상은 실제 워크로드 근거로 검증해야 합니다.',startsWith:'공개 기술 검토 또는 별도로 선택된 평가.',ctaLabel:'기술 검토 요청'}
};
export function useCaseCopy(locale:string,u:UseCase):UseCase{return locale==='ko'?{...u,...KO[u.slug]}:u;}
